cREATE TABLE MEMBER_INFO(
MEMID varchar2(30) PRIMARY KEY, -- (man01~5,girl01~5 순서대로)
PASSWORD varchar2(50), --(1111,2222,~5555 위 ID 숫자와 맵핑)
NAME VARCHAR2(20), --(한국에서 가장 많이 사용되는 이름 남자이름5개 여자이름5개 순서대로)
ADDRESS VARCHAR2(50), -- (서울시 테헤란로 21길 6번지와 같은 형태로 랜덤으로 서울, 경기권 주소)
CONTACT VARCHAR2(50), --(010-1111-1111~010-5555,5555 처럼 남자여자 순서대로 맵핑)
EMAIL VARCHAR2(50) -- (man01@gmail.com~girl05@gmail.com 순서대로)
);
SELECT *FROM MEMBER_info;
DROP TABLE MEMBER_info;
SELECT MEMID,PASSWORD
FROM MEMBER_info
WHERE MEMID='man01' AND PASSWORD='aaaa1111';

INSERT INTO MEMBER_INFO values('vanana','7777','노현우','서울 강서구','010-1111-2345','ggg1234@naver.com');

INSERT ALL
    INTO MEMBER_INFO (MEMID, PASSWORD, NAME, ADDRESS, CONTACT, EMAIL) VALUES ('man01', 'AAaa11##', '홍길동', '서울시 테헤란로 21길 6', '010-1111-1111', 'man01@gmail.com')
    INTO MEMBER_INFO (MEMID, PASSWORD, NAME, ADDRESS, CONTACT, EMAIL) VALUES ('man02', 'BBbb22##', '이순신', '서울시 강남구 역삼동 123번지', '010-2222-2222', 'man02@gmail.com')
    INTO MEMBER_INFO (MEMID, PASSWORD, NAME, ADDRESS, CONTACT, EMAIL) VALUES ('man03', 'CCcc33##', '김철수', '경기도 수원시 영통구 정자동 456번지', '010-3333-3333', 'man03@gmail.com')
    INTO MEMBER_INFO (MEMID, PASSWORD, NAME, ADDRESS, CONTACT, EMAIL) VALUES ('man04', 'DDdd44##', '박영희', '서울시 강서구 옥길동 101번지', '010-4444-4444', 'man04@gmail.com')
    INTO MEMBER_INFO (MEMID, PASSWORD, NAME, ADDRESS, CONTACT, EMAIL) VALUES ('man05', 'EEee55##', '정미경', '경기도 광명시 화곡동 234번지', '010-5555-5555', 'man05@gmail.com')
    INTO MEMBER_INFO (MEMID, PASSWORD, NAME, ADDRESS, CONTACT, EMAIL) VALUES ('girl01', 'FFff11##', '김영자', '서울시 강북구 미아동 567번지', '010-1111-1111', 'girl01@gmail.com')
    INTO MEMBER_INFO (MEMID, PASSWORD, NAME, ADDRESS, CONTACT, EMAIL) VALUES ('girl02', 'GGgg22##', '이미림', '경기도 성남시 중원구 백석동 890번지', '010-2222-2222', 'girl02@gmail.com')
    INTO MEMBER_INFO (MEMID, PASSWORD, NAME, ADDRESS, CONTACT, EMAIL) VALUES ('girl03', 'HHhh33##', '박서영', '서울시 관악구 봉천동 123번지', '010-3333-3333', 'girl03@gmail.com')
    INTO MEMBER_INFO (MEMID, PASSWORD, NAME, ADDRESS, CONTACT, EMAIL) VALUES ('girl04', 'IIii44##', '최현주', '경기도 용인시 수지구 인계동 456번지', '010-4444-4444', 'girl04@gmail.com')
    INTO MEMBER_INFO (MEMID, PASSWORD, NAME, ADDRESS, CONTACT, EMAIL) VALUES ('girl05', 'JJjj55##', '정지은', '서울시 관악구 사당동 789번지', '010-5555-5555', 'girl05@gmail.com')
SELECT 1 FROM DUAL;






CREATE TABLE ALCOHOL(
ALCOHOL_ID VARCHAR2(50),
ALCOHOL_NAME VARCHAR2(50),
TYPE_ID VARCHAR2(50),
ALCOHOL_DEG NUMBER,
ALCOHOL_PRICE NUMBER,
ALCOHOL_VOL NUMBER,
EXPDATE DATE,
STORAGE_WAY VARCHAR2(30),
ALCOHOL_IMG VARCHAR2(50),
ALCOHOL_DES VARCHAR2(50),
CONSTRAINT alcohol_pk PRIMARY KEY (ALCOHOL_ID),
CONSTRAINT alcohol_fk FOREIGN KEY (TYPE_ID) REFERENCES ALCOHOL_TYPE(TYPE_ID),
CONSTRAINT alcohol_fk1 FOREIGN KEY (TYPE_ID) REFERENCES ALCOHOL(TYPE_ID)
);

CREATE TABLE alcohol_type (
TYPE_ID VARCHAR2(50) PRIMARY KEY,
TYPE_NAME VARCHAR2(50)
);

INSERT INTO alcohol values('서울주','탁주',30,10000,350,sysdate + (INTERVAL'2'YEAR),'상온보관','/source','서울에서 만듬');

CREATE TABLE SNACK (
SNACK_ID VARCHAR2(50),
SNACK_NAME VARCHAR2(50),
CATEGORY_ID VARCHAR2(50),
SNACK_BRAND VARCHAR2(50),
SNACK_PRICE NUMBER,
SNACK_IMG VARCHAR2(50),
SNACK_DES VARCHAR2(50),
CONSTRAINT snack_pk PRIMARY KEY (snack_id),
CONSTRAINT snack_fk FOREIGN KEY (category_id) REFERENCES snack_category(category_id),
CONSTRAINT snack_fk1 FOREIGN KEY (category_id) REFERENCES snack(category_id)
);

CREATE TABLE SNACK_CATEGORY (
CATEGORY_ID VARCHAR2(50) PRIMARY KEY,
CATEGORY_NAME VARCHAR2(50)
);


INSERT INTO snack values('어묵탕','탕/국/찌개','비비고',10000,'/source','어묵탕입니다.');

CREATE TABLE CART (
CART_NUM VARCHAR2(50) PRIMARY KEY,
CNT NUMBER,
TOTAL_PRICE NUMBER,
SNACK_NAME VARCHAR2(50),
ALCOHOL_NAME VARCHAR2(50),
MEMID varchar2(30),
FOREIGN KEY (SNACK_NAME) REFERENCES SNACK(SNACK_NAME),
FOREIGN KEY (ALCOHOL_NAME) REFERENCES ALCOHOL(ALCOHOL_NAME),
FOREIGN KEY (MEMID) REFERENCES MEMBER_INFO(MEMID)
);

CREATE TABLE SUB_PRODUCT (
SUB_PRODNUM VARCHAR2(50) PRIMARY KEY,
SNACK_NAME VARCHAR2(50),
ALCOHOL_NAME VARCHAR2(50),
FOREIGN KEY (SNACK_NAME) REFERENCES SNACK(SNACK_NAME),
FOREIGN KEY (ALCOHOL_NAME) REFERENCES ALCOHOL(ALCOHOL_NAME)
);

CREATE TABLE SUB_PAY (
SUB_PAYNUM VARCHAR2(50) PRIMARY KEY,
SUB_PAYDATE DATE,
SUB_PAYARRIVE DATE,
SUB_PAYMETHOD VARCHAR2(30),
MEMID varchar2(30),
SUB_PRODNUM VARCHAR2(50),
FOREIGN KEY (MEMID) REFERENCES MEMBER_INFO(MEMID),
FOREIGN KEY (SUB_PRODNUM) REFERENCES SUB_PRODUCT(SUB_PRODNUM)
);

CREATE TABLE SUB_MEM (
SUB_PAYNUM VARCHAR2(50) PRIMARY KEY,
FOREIGN KEY (SUB_PAYNUM) REFERENCES SUB_PAY(SUB_PAYNUM)
);

CREATE TABLE SUB_DELIVERY (
SUB_DEVNUM VARCHAR2(50) PRIMARY KEY,
SUB_PAYNUM VARCHAR2(50),
FOREIGN KEY (SUB_PAYNUM) REFERENCES SUB_PAY(SUB_PAYNUM)
);


CREATE TABLE ORDERS (
ORDERS_NUM VARCHAR2(50) PRIMARY KEY,
CART_NUM VARCHAR2(50),
ORDERS_DATE DATE,
FOREIGN KEY (CART_NUM) REFERENCES CART(CART_NUM)
);

CREATE TABLE STORE_PAY (
ORDERS_NUM VARCHAR2(50) PRIMARY KEY,
PAY_METHOD VARCHAR2(20),
FOREIGN KEY (ORDERS_NUM) REFERENCES ORDERS(ORDERS_NUM)
);

CREATE TABLE STORE_DELIVERY (
DELIVERY_NUM VARCHAR2(50) PRIMARY KEY,
ORDERS_NUM VARCHAR2(50),
FOREIGN KEY (ORDERS_NUM) REFERENCES ORDERS(ORDERS_NUM)
);



DROP TABLE ALCOHOL; 
DROP TABLE MEMBER_INFO; 
DROP TABLE SNACK ; 


